services:
  dev-container-sidiff:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-container-sidiff
    # mem_limit: 10g
    ports:
      - "127.0.0.1:3000:3000" # HTTP access: https://localhost:3000/
      # - "127.0.0.1:3001:3001" # HTTPS access: https://localhost:3001/
      # - "127.0.0.1:3002:6901" # HTTPS access (direct KasmVNC, no audio): https://localhost:3002/
    security_opt:
      - seccomp=unconfined # modern GUI desktop apps have issues with the latest Docker and syscall compatibility
    volumes:
      - dev_container_data_sidiff:/config # user directory
      # See Dockerfile for configuration description:
      # - ./eclipse-workspace:/config/workspace/eclipse-workspace
      - ./eclipse-workspace/.metadata/version.ini:/config/workspace/eclipse-workspace/.metadata/version.ini
      - ./eclipse-workspace/.metadata/.plugins/org.eclipse.core.resources/:/config/workspace/eclipse-workspace/.metadata/.plugins/org.eclipse.core.resources/
      - ./eclipse-workspace/.metadata/.plugins/org.eclipse.core.resources/0.snap:/config/workspace/eclipse-workspace/.metadata/.plugins/org.eclipse.core.resources/0.snap
      - ./eclipse-workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.egit.core.prefs:/config/workspace/eclipse-workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.egit.core.prefs
      - ./eclipse-workspace/.metadata/.plugins/org.eclipse.debug.core/.launches/Eclipse-SiDiff.launch:/config/workspace/eclipse-workspace/.metadata/.plugins/org.eclipse.debug.core/.launches/Eclipse-SiDiff.launch
      - ./eclipse-workspace/.metadata/.plugins/org.eclipse.debug.ui/launchConfigurationHistory.xml:/config/workspace/eclipse-workspace/.metadata/.plugins/org.eclipse.debug.ui/launchConfigurationHistory.xml
      - ./eclipse-workspace/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi:/config/workspace/eclipse-workspace/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
      - ./eclipse-workspace/.metadata/.plugins/org.eclipse.ui.workbench/workingsets.xml:/config/workspace/eclipse-workspace/.metadata/.plugins/org.eclipse.ui.workbench/workingsets.xml
      # - ./runtime-eclipse-workspace-sidiff/:/config/workspace/runtime-eclipse-workspace-sidiff/
      - ./runtime-eclipse-workspace-sidiff/org.sidiff.editrule.generator.serge.config.ecore/:/config/workspace/runtime-eclipse-workspace-sidiff/org.sidiff.editrule.generator.serge.config.ecore/
      - ./runtime-eclipse-workspace-sidiff/.metadata/version.ini:/config/workspace/runtime-eclipse-workspace-sidiff/.metadata/version.ini
      - ./runtime-eclipse-workspace-sidiff/.metadata/.plugins/org.eclipse.core.resources/:/config/workspace/runtime-eclipse-workspace-sidiff/.metadata/.plugins/org.eclipse.core.resources/
      - ./runtime-eclipse-workspace-sidiff/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi:/config/workspace/runtime-eclipse-workspace-sidiff/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
      - ./runtime-eclipse-workspace-sidiff/.metadata/.plugins/org.eclipse.ui.workbench/workingsets.xml:/config/workspace/runtime-eclipse-workspace-sidiff/.metadata/.plugins/org.eclipse.ui.workbench/workingsets.xml
    environment:
      - LIBGL_ALWAYS_SOFTWARE=1  # enable software rendering for the desktop
      - PUID=1000 # user PUID
      - PGID=1000 # group PGID
      - TZ=Europe/Zurich # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
      - TITLE=Dev-SiDiff # the page title displayed on the web browser
      # - PASSWORD=nUuuDn*R6Q3$9^gzn0gR # HTTP Basic auth password, abc is default. If unset there will be no auth
    shm_size: "1gb" # we set this to 1 gig to prevent modern web browsers from crashing
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          device_ids: ["all"]  # Select specific GPUs with "0", "1", ...
    #          capabilities: [gpu]  # Set environment: LIBGL_ALWAYS_SOFTWARE=0

volumes:
  dev_container_data_sidiff: